name: Deploy Pages
run-name: ${{ github.actor }} is building and deploying the site
on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch
    paths:
      - "docs/**"
      - ".github/workflows/build_and_deploy_jekyll.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: docs

      - name: Build Jekyll site
        working-directory: docs
        run: bundle exec jekyll build --destination ../_site

      - name: Publish generated site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy-pages
          publish_dir: ./_site
          enable_jekyll: false
